// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: byzantine.proto

package byzantine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Byzantine_SendMessage_FullMethodName = "/byzantine.Byzantine/SendMessage"
)

// ByzantineClient is the client API for Byzantine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Byzantine service defines a single RPC for sending messages.
type ByzantineClient interface {
	SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type byzantineClient struct {
	cc grpc.ClientConnInterface
}

func NewByzantineClient(cc grpc.ClientConnInterface) ByzantineClient {
	return &byzantineClient{cc}
}

func (c *byzantineClient) SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, Byzantine_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ByzantineServer is the server API for Byzantine service.
// All implementations must embed UnimplementedByzantineServer
// for forward compatibility.
//
// The Byzantine service defines a single RPC for sending messages.
type ByzantineServer interface {
	SendMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedByzantineServer()
}

// UnimplementedByzantineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedByzantineServer struct{}

func (UnimplementedByzantineServer) SendMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedByzantineServer) mustEmbedUnimplementedByzantineServer() {}
func (UnimplementedByzantineServer) testEmbeddedByValue()                   {}

// UnsafeByzantineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ByzantineServer will
// result in compilation errors.
type UnsafeByzantineServer interface {
	mustEmbedUnimplementedByzantineServer()
}

func RegisterByzantineServer(s grpc.ServiceRegistrar, srv ByzantineServer) {
	// If the following call pancis, it indicates UnimplementedByzantineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Byzantine_ServiceDesc, srv)
}

func _Byzantine_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByzantineServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byzantine_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByzantineServer).SendMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Byzantine_ServiceDesc is the grpc.ServiceDesc for Byzantine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Byzantine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "byzantine.Byzantine",
	HandlerType: (*ByzantineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Byzantine_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "byzantine.proto",
}
